spring:
  application:
    name: SITAS
  datasource:
    url: jdbc:oracle:thin:@192.168.30.68:1521/xe
    username: SYSTEM
    password: F4br1c43sc23l4
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect
  mail:
    host: smtp.example.com
    port: 587
    username: airline@udea.edu.co
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

airline-api:
  openapi:
    dev-url: http://localhost:8007/

server:
  port: 8007
  servlet:
    context-path: /modulo-07
  ssl:
    key-store: classpath:codefact.p12
    key-store-password: 123456
    enabled-protocols: TLSv1.2
    key-store-type: PKCS12
logging:
  level:
    spring-boot-web: DEBUG
    root: DEBUG
    org.springframework: DEBUG



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "CheckinApplication"

springdoc:
  packages-to-scan: "package1, package2, com.sitas.checkin"
  paths-to-match: "/v1, /api/balance/**, *, **, /*, /**"