spring:
  application:
    name: checkin
  datasource:
    url: jdbc:oracle:thin:@host.docker.internal:1521/free
    username: system
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.OracleDialect
  mail:
    host: smtp.example.com
    port: 587
    username: airline@udea.edu.co
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

airline-api:
  openapi:
    dev-url: http://localhost:8080/
server:
  port: 8080
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "CheckinApplication"

springdoc:
  packages-to-scan: "package1, package2, com.sitas.checkin"
  paths-to-match: "/v1, /api/balance/**, *, **, /*, /**"