name: Docker Image CI

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKER}}

      - name: selena quintanilla
        run: ls -a
      - name: docker2
        run: |
          docker build -t oracle . -f ./Dockerfile
          docker tag oracle ${{secrets.DOCKERUSERNAME}}/oracle:version0.0.0
          docker push ${{secrets.DOCKERUSERNAME}}/oracle:version0.0.0
          
      
      #- name: build docker image
        #uses: docker/build-push-action@v4 
        #with: 
          #context: .
          #file: ./Dockerfile
          #push: true
         # tags: ${{secrets.DOCKERUSERNAME}}/oracle:version0.0.0
          
