name: Docker Image CI

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
          
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKER}}

      - name: docker compositador
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./compose.yml"
      
