name: Docker Image CI

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
          
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: restrepotorres
          password: ${{secrets.DOCKER}}

      - name: build docker compose
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./compose.yaml"

      - name: push from docker compose
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: 'compose.yaml' # required
          repo_token: ${{ secrets.DOCKER }}
