name: Docker Image CI

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKER}}
      - name: build docker image
        uses: docker/build-push-action@v4 
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERUSERNAME}}/oracle:version0.0.0
